### ISSUE TITLE
Separate "Discussion"

### ISSUE THREAD

**Issue by antonlegoo** [myfossil/myfossil-specimen#69]
Currently, it almost appears as if "Discussion" is just another information section, e.g. "Geochronology".

With the amount of information on this page being very dense, I believe it would helpful to separate the main information section from the "Discussion"- which could get very long and piece-y. 

Below is a screenshot of how this could look.

![screen shot 2015-01-09 at 2 51 39 pm](https://cloud.githubusercontent.com/assets/1424526/5688797/54d57a04-9810-11e4-8760-40a8724f1f2e.png)

**Comment by woodb** [comment]
Closing as a duplicate to #70
